name: Deploy Backend

on:
  push:
    branches:
      - dev-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Demo-Backend-projects
            git pull origin dev-branch
            npm install
            pm2 restart server
            pm2 save
